name: Deploy CDK

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4 # Updated to v4
        with:
          role-to-assume: arn:aws:iam::566348719618:role/Github-Actions
          aws-region: eu-west-2

      - name: Install Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '22'
          cache: 'yarn' # Caches dependencies for faster runs

      - name: Install dependencies
        run:  yarn install --immutable  # Uses PnP caching for faster installs

      - name: Build project
        run: yarn build

      - name: Deploy CDK Stack
        run: npx cdk deploy --require-approval never